apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mentalist
    tier: challenge
  name: mentalist
spec:
  replicas: 3
  template:
    metadata:
      annotations:
        apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
        seccomp.security.alpha.kubernetes.io/pod: docker/default
      labels:
        app: mentalist
        networkpolicy: allow_egress
        tier: challenge
    spec:
      automountServiceAccountToken: false
      containers:
      - env: []
        image: gcr.io/bsides-sf-ctf-2020/mentalist
        name: mentalist
        ports:
        - containerPort: 12345
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
      volumes: []
